In [19]:
### Loading traindata from csv, read and display storing in trainData
import numpy as np
import sklearn as sk
import os
trainData = np.genfromtxt("/Users/panigrahirenuka/PythonPractice/JupyterNotebook/trainData.csv", delimiter=",", skip_header=1)
trainData


array([[0.639, 0.099, 0.   ],
       [0.025, 0.686, 0.   ],
       [0.275, 0.544, 0.   ],
       ...,
       [0.55 , 0.062, 0.   ],
       [0.455, 0.138, 0.   ],
       [0.315, 0.207, 0.   ]])

In [20]:
### Separating the third off set in the  trainData numpy array by slicing it and giving name as trainLabels
trainLabels= trainData[:,2]
trainLabels

array([0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0.,
       1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1.,
       0., 1., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1.,
       1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1.,
       0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       0., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1.,
       0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 0.,
       1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1.,
       1., 0., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       1., 0., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1.,
       1., 1., 0., 0., 1.

In [4]:
### Storing the first two rows of the TrainData in trainFeatures by numpy array slicing
trainFeatures= trainData[:,1]
trainFeatures

array([0.099, 0.686, 0.544, 0.978, 0.359, 0.398, 0.19 , 0.122, 0.848,
       0.455, 0.663, 0.642, 0.597, 0.021, 0.787, 0.244, 0.126, 0.565,
       0.069, 0.765, 0.207, 0.216, 0.87 , 0.329, 0.148, 0.901, 0.003,
       0.858, 0.145, 0.13 , 0.251, 0.174, 0.661, 0.026, 0.015, 0.79 ,
       0.238, 0.324, 0.174, 0.052, 0.742, 0.526, 0.746, 0.476, 0.778,
       0.513, 0.109, 0.504, 0.945, 0.043, 0.783, 0.867, 0.521, 0.458,
       0.964, 0.061, 0.479, 0.402, 0.686, 0.49 , 0.91 , 0.073, 0.081,
       0.608, 0.066, 0.275, 0.633, 0.548, 0.325, 0.995, 0.531, 0.454,
       0.605, 0.099, 0.702, 0.853, 0.651, 0.769, 0.721, 0.215, 0.452,
       0.228, 0.339, 0.453, 0.416, 0.095, 0.427, 0.665, 0.374, 0.153,
       0.923, 0.067, 0.832, 0.093, 0.097, 0.739, 0.812, 0.556, 0.586,
       0.562, 0.33 , 0.122, 0.354, 0.665, 0.75 , 0.868, 0.721, 0.968,
       0.6  , 0.352, 0.578, 0.213, 0.657, 0.224, 0.108, 0.845, 0.368,
       0.763, 0.574, 0.807, 0.845, 0.975, 0.818, 0.614, 0.643, 0.026,
       0.929, 0.829,

In [5]:
### Loading testData from csv, read and display and storing in testData
import numpy as np
testData = np.genfromtxt("/Users/panigrahirenuka/PythonPractice/JupyterNotebook/testData.csv", delimiter=",",skip_header=1)
testData

array([[0.97 , 0.662, 1.   ],
       [0.404, 0.525, 1.   ],
       [0.515, 0.314, 1.   ],
       [0.988, 0.173, 1.   ],
       [0.658, 0.912, 1.   ],
       [0.543, 0.342, 1.   ],
       [0.413, 0.354, 1.   ],
       [0.188, 0.772, 1.   ],
       [0.362, 0.721, 1.   ],
       [0.756, 0.643, 1.   ],
       [0.625, 0.693, 1.   ],
       [0.76 , 0.61 , 1.   ],
       [0.204, 0.192, 0.   ],
       [0.549, 0.247, 1.   ],
       [0.928, 0.558, 1.   ],
       [0.438, 0.225, 0.   ],
       [0.698, 0.973, 1.   ],
       [0.121, 0.298, 0.   ],
       [0.973, 0.289, 1.   ],
       [0.609, 0.207, 0.   ],
       [0.239, 0.705, 1.   ],
       [0.158, 0.317, 0.   ],
       [0.551, 0.349, 1.   ],
       [0.552, 0.934, 1.   ],
       [0.093, 0.795, 0.   ],
       [0.992, 0.273, 1.   ],
       [0.913, 0.122, 1.   ],
       [0.461, 0.677, 1.   ],
       [0.117, 0.38 , 0.   ],
       [0.832, 0.98 , 1.   ],
       [0.498, 0.818, 1.   ],
       [0.717, 0.955, 1.   ],
       [0.509, 0.805, 1.   ],
       [0.

In [6]:
### get the third offset in the testData array and storing in testLabels
testLabels= testData[:,2]
testLabels

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0.,
       1., 1., 0., 1., 0., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1.,
       0., 1., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 1.,
       0., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0.,
       1., 1., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 0., 1.,
       0., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       0., 1., 0., 1., 0., 1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1.,
       1., 0., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       1., 1., 1., 1., 0.

In [7]:
### getting the first two rows of the testData and storing in testFeatures
testFeatures= testData[:,1]
testFeatures

array([0.662, 0.525, 0.314, 0.173, 0.912, 0.342, 0.354, 0.772, 0.721,
       0.643, 0.693, 0.61 , 0.192, 0.247, 0.558, 0.225, 0.973, 0.298,
       0.289, 0.207, 0.705, 0.317, 0.349, 0.934, 0.795, 0.273, 0.122,
       0.677, 0.38 , 0.98 , 0.818, 0.955, 0.805, 0.29 , 0.288, 0.714,
       0.346, 0.442, 0.256, 0.479, 0.202, 0.539, 0.933, 0.696, 0.137,
       0.616, 0.587, 0.242, 0.67 , 0.531, 0.638, 0.052, 0.413, 0.717,
       0.101, 0.771, 0.005, 0.55 , 0.929, 0.407, 0.935, 0.878, 0.477,
       0.199, 0.964, 0.321, 0.646, 0.908, 0.089, 0.574, 0.535, 0.723,
       0.937, 0.913, 0.175, 0.882, 0.176, 0.92 , 0.997, 0.397, 0.495,
       0.937, 0.962, 0.926, 0.877, 0.009, 0.568, 0.107, 0.983, 0.285,
       0.989, 0.543, 0.494, 0.939, 0.851, 0.468, 0.193, 0.113, 0.162,
       0.459, 0.257, 0.186, 0.737, 0.791, 0.568, 0.757, 0.175, 0.856,
       0.897, 0.827, 0.515, 0.087, 0.669, 0.185, 0.141, 0.324, 0.248,
       0.261, 0.236, 0.754, 0.954, 0.302, 0.723, 0.011, 0.654, 0.693,
       0.062, 0.118,

In [8]:
### import the DecisionTreeClassifier module 
from sklearn.tree import DecisionTreeClassifier

In [9]:
## create a decision tree classifier object. 
## This is a raw tree, no data has been given to train it.
## We are using all the default parameters for the ClassificationTree() constructor.
## There are a large number of parameters you can give to the constructor, see documentation

clf=DecisionTreeClassifier()

In [10]:
## Fit the tree with training data
## The output shows the default values of parameters used by the constructor
## The split condition used is 'gini' 

clf.fit(trainData, trainLabels)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [11]:
### Now use the model to predict labels for test data:
pred=clf.predict(testData)

In [12]:
print(pred) ## These are the class labels the model predicts

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 1. 1.
 0. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 0. 1. 0. 1. 0. 1. 1. 1. 0. 1. 1. 1.
 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 0. 1. 1. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1.
 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 1. 0. 1. 1. 1. 1. 1. 0.
 0. 0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1.
 1. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 1. 1. 1. 0. 1. 0. 1. 1. 0. 0. 1. 1. 0.
 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 0. 1. 0. 1. 1. 1. 0. 1. 1. 0. 1. 1. 0.
 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 1. 1. 1. 1. 0. 1. 1. 1.
 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 0. 1. 1. 0. 1. 0.
 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 0. 1. 0. 1. 0. 1. 1. 0. 0. 1. 0.
 0. 1. 1. 1. 0. 1. 1. 1. 1.]


In [13]:
### To calculate the accuracy of the model, compare how many test labels 
### correspond to predicted class labels 
print(testLabels)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 1. 1.
 0. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 0. 1. 0. 1. 0. 1. 1. 1. 0. 1. 1. 1.
 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 0. 1. 1. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1.
 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 1. 0. 1. 1. 1. 1. 1. 0.
 0. 0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1.
 1. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 1. 1. 1. 0. 1. 0. 1. 1. 0. 0. 1. 1. 0.
 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 0. 1. 0. 1. 1. 1. 0. 1. 1. 0. 1. 1. 0.
 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 1. 1. 1. 1. 0. 1. 1. 1.
 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 0. 1. 1. 0. 1. 0.
 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 0. 1. 0. 1. 0. 1. 1. 0. 0. 1. 0.
 0. 1. 1. 1. 0. 1. 1. 1. 1.]


In [14]:
### You can see that all but one predicted label correspond to the test labels.
### You can find the accuracy of the model as follows:
sum(pred==testLabels)/len(pred)

1.0

In [16]:
from sklearn.externals.six import StringIO  
from IPython.display import Image  
from sklearn.tree import export_graphviz
import pydotplus

In [1]:
### displaying a decision tree by using the graphviz and pydotplus in python by using the trainfeature,testfeatues, testlabels data as the size of the array is 3 rows, need to pass 3 attributes inside features.

dot_data = StringIO()
export_graphviz(clf, out_file=dot_data,  
                filled=True, rounded=True, feature_names=["Attribute1", "Attribute2","Labels"],
                special_characters=True)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())
Image(graph.create_png())

NameError: name 'StringIO' is not defined