In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('homeprices1.csv')
df

Unnamed: 0  area  bedrooms  age   price
0           0  2600       3.0   20  550000
1           1  3000       4.0   15  565000
2           2  3200       NaN   18  610000
3           3  3600       3.0   30  595000
4           4  4000       5.0    8  760000

In [4]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

3

In [5]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

Unnamed: 0  area  bedrooms  age   price
0           0  2600       3.0   20  550000
1           1  3000       4.0   15  565000
2           2  3200       3.0   18  610000
3           3  3600       3.0   30  595000
4           4  4000       5.0    8  760000

In [6]:
 reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [7]:
plt.clf() ## clear current figure
plt.scatter(area, bedrooms,age, color="b", label="data read-in")
plt.plot(price, reg.predict(price), color="black", label="regression line")
plt.legend()
plt.xlabel("area")
plt.ylabel("bedrooms")
plt.zlabel("age")

NameError: name 'area' is not defined

<Figure size 432x288 with 0 Axes>

In [9]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [10]:
reg.intercept_

383724.99999999994

In [14]:
reg.predict([[3000,3,40]])

array([444400.])

In [15]:
 137.25*3000+-26025*3+-6825.*40+383724.99999999994

444399.99999999994

In [16]:
reg.predict([[2500,4,5]])

array([588625.])