In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt
from scipy.interpolate import *

In [2]:
cigarettes = np.genfromtxt('cigarettes_multi_regression.csv', delimiter=',',skip_header=1)


In [3]:
cigarettes[:,1:3]

array([[14.1 ,  0.86],
       [16.  ,  1.06],
       [29.8 ,  2.03],
       [ 8.  ,  0.67],
       [ 4.1 ,  0.4 ],
       [15.  ,  1.04],
       [ 8.8 ,  0.76],
       [12.4 ,  0.95],
       [16.6 ,  1.12],
       [14.9 ,  1.02],
       [13.7 ,  1.01],
       [15.1 ,  0.9 ],
       [ 7.8 ,  0.57],
       [11.4 ,  0.78],
       [ 9.  ,  0.74],
       [ 1.  ,  0.13],
       [17.  ,  1.26],
       [12.8 ,  1.08],
       [15.8 ,  0.96],
       [ 4.5 ,  0.42],
       [14.5 ,  1.01],
       [ 7.3 ,  0.61],
       [ 8.6 ,  0.69],
       [15.2 ,  1.02],
       [12.  ,  0.82]])

In [4]:
CO = cigarettes[:,4]
CO

array([13.6, 16.6, 23.5, 10.2,  5.4, 15. ,  9. , 12.3, 16.3, 15.4, 13. ,
       14.4, 10. , 10.2,  9.5,  1.5, 18.5, 12.6, 17.5,  4.9, 15.9,  8.5,
       10.6, 13.9, 14.9])

In [5]:
X = cigarettes[:,1:3]

In [6]:
Y = cigarettes[:,4]

In [7]:
 reg = linear_model.LinearRegression()
reg.fit(X,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [8]:
reg.intercept_

3.0896092639396855

In [9]:
reg.coef_

array([ 0.9624741 , -2.64627213])

In [20]:
Y = cigarettes[:,4].reshape(1,-1)
Y
Y.shape

(1, 25)

In [22]:
X = cigarettes[:,1:3].reshape(1,-1)
X.shape

(1, 50)

In [107]:
from sklearn.metrics import r2_score
score=r2_score(CO,pred)
score

0.918584975710395

In [110]:
len(TarNicotine) == len(CO)

True

In [137]:
plt(X,Y,'o')

TypeError: 'module' object is not callable