In [10]:
import numpy as np
import sklearn as sk
import matplotlib.pyplot as plt
from sklearn import linear_model

In [11]:
cigData=np.genfromtxt('cigarettes_multi_regression.csv',delimiter=',', skip_header=1) 
cigData.shape

(25, 5)

In [12]:
x = cigData[0:20,1:4]
x
#cigX.shape

array([[14.1   ,  0.86  ,  0.9853],
       [16.    ,  1.06  ,  1.0938],
       [29.8   ,  2.03  ,  1.165 ],
       [ 8.    ,  0.67  ,  0.928 ],
       [ 4.1   ,  0.4   ,  0.9462],
       [15.    ,  1.04  ,  0.8885],
       [ 8.8   ,  0.76  ,  1.0267],
       [12.4   ,  0.95  ,  0.9225],
       [16.6   ,  1.12  ,  0.9372],
       [14.9   ,  1.02  ,  0.8858],
       [13.7   ,  1.01  ,  0.9643],
       [15.1   ,  0.9   ,  0.9316],
       [ 7.8   ,  0.57  ,  0.9705],
       [11.4   ,  0.78  ,  1.124 ],
       [ 9.    ,  0.74  ,  0.8517],
       [ 1.    ,  0.13  ,  0.7851],
       [17.    ,  1.26  ,  0.9186],
       [12.8   ,  1.08  ,  1.0395],
       [15.8   ,  0.96  ,  0.9573],
       [ 4.5   ,  0.42  ,  0.9106]])

In [13]:
y = cigData[0:20,4]
y.shape

(20,)

In [14]:
regCig=sk.linear_model.LinearRegression()
regCig.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [15]:
regCig.coef_

array([ 0.95275481, -1.71169801, -4.96397312])

In [16]:
regCig.intercept_

6.958761887929783

In [17]:
def regressionMetrics(x, y):
    """ Uses linaer_model.LinearRegression class to find the regression model using x, y data.
        Function returns SSR, SSE, SST, r^2 calculated as SSR/SST and r^2 from regression model 
    """
    regModel=linear_model.LinearRegression()
    regModel.fit(x,y)
    y_hat=regModel.predict(x)
    y_mean=np.mean(y)
    ssr = np.sum(np.square(y_hat-y_mean))
    sse = np.sum(np.square(y-y_hat))
    sst = np.sum(np.square(y-y_mean))
    r_squared=ssr/sst
    score=regModel.score(x, y)
    return ssr, sse, sst, r_squared, score

In [18]:
ssr, sse, sst, r_squared, score =  regressionMetrics(x,y)

In [19]:
ssr

470.4416418968678

In [20]:
sse

29.820358103132296

In [21]:
sst

500.26200000000006

In [22]:
r_squared

0.9403905191616948

In [33]:
x = cigData[20:25,1:4]
x

array([[14.5   ,  1.01  ,  1.007 ],
       [ 7.3   ,  0.61  ,  0.9806],
       [ 8.6   ,  0.69  ,  0.9693],
       [15.2   ,  1.02  ,  0.9496],
       [12.    ,  0.82  ,  1.1184]])

In [34]:
y = cigData[20:25, 4]
y

array([15.9,  8.5, 10.6, 13.9, 14.9])

In [43]:
regCig=sk.linear_model.LinearRegression()
regCig.fit(x,y)
regCig.score(x,y)

0.987703562356782

In [36]:
regCig.coef_

array([-1.39221419, 41.00378658, 27.74218481])

In [37]:
regCig.intercept_

-33.1151762583816

In [38]:
ssr, sse, sst, r_squared, score =  regressionMetrics(x,y)

In [39]:
ssr

38.07794773597868

In [40]:
sse

0.4740522640213334

In [41]:
sst

38.55200000000001

In [42]:
r_squared

0.9877035623567825